# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx_log
    static_configs:
      - targets:
          - localhost
        labels:
          job: "nginx"
          __path__: /var/log/*.log
    pipeline_stages:
    - match:
        selector: '{job="nginx"}'
        stages:
          - regex:
              expression: '^(?P<timestamp>\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<log_level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): \*(?P<connection_id>\d+) (?P<message>.*), client: (?P<client_ip>[^,]+), server: (?P<server>[^,]+), request: "(?P<method>\S+) (?P<request>[^"]+) (?P<protocol>\S+)", upstream: "(?P<upstream>[^"]+)", host: "(?P<host>[^"]+)"'
          - labels:
              timestamp:
              log_level:
              pid:
              tid:
              connection_id:
              message:
              client_ip:
              server:
              method:
              request:
              protocol:
              upstream:
              host:
          - timestamp:
              # Mon Jan 2 15:04:05 -0700 MST 2006
              format: 2006/1/2 15:04:05
              source: timestamp
    - match:
        selector: '{job="nginx"}'
        stages:
          - regex:
              expression: '^(?P<client_ip>\S+) \S+ \S+ \[(?P<timestamp>[^\]]+)\] "(?P<method>\S+) (?P<request>[^"]+) (?P<protocol>\S+)" (?P<status>\d+) (?P<bytes_sent>\d+) "(?P<referer>[^"]*)" "(?P<user_agent>[^"]*)" (?P<request_length>\d+) (?P<request_time>\S+) \[(?P<proxy_upstream_name>[^\]]*)\] \[(?P<proxy_alternative_upstream_name>[^\]]*)\] (?P<upstream_addr>\S+) (?P<upstream_response_length>\d+) (?P<upstream_response_time>\S+) (?P<upstream_status>\d+) (?P<req_id>\S+)$'
          - labels:
              client_ip:
              method:
              request:
              status:
              timestamp:
              # protocol:
              bytes_sent:
              # referer:
              # user_agent:
              request_length:
              request_time:
              # proxy_upstream_name:
              # proxy_alternative_upstream_name:
              # upstream_addr:
              upstream_response_length:
              upstream_response_time:
              upstream_status:
              # req_id:
          - timestamp:
              # Mon Jan 2 15:04:05 -0700 MST 2006
              format: 02/Jan/2006:15:04:05 -0700
              source: timestamp
